# Generated by Django 3.2.7 on 2022-06-14 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
            ],
        ),
        migrations.CreateModel(
            name='Men',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('content', models.TextField(blank=True, verbose_name='post text')),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='celebrity photo')),
                ('time_create', models.DateField(auto_now_add=True, verbose_name='post created')),
                ('time_update', models.DateField(auto_now=True)),
                ('is_published', models.BooleanField(default=True, verbose_name='publication')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blog.category', verbose_name='category')),
            ],
            options={
                'verbose_name': 'Popular man',
                'verbose_name_plural': 'Popular men',
                'ordering': ['time_create', 'title'],
            },
        ),
    ]
