# Generated by Django 3.2.7 on 2022-06-12 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20220609_0107'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='men',
            options={'ordering': ['time_create', 'title'], 'verbose_name': 'Popular man', 'verbose_name_plural': 'Popular men'},
        ),
        migrations.AlterField(
            model_name='men',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='blog.category', verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='men',
            name='content',
            field=models.TextField(blank=True, verbose_name='post text'),
        ),
        migrations.AlterField(
            model_name='men',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='publication'),
        ),
        migrations.AlterField(
            model_name='men',
            name='photo',
            field=models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='celebrity photo'),
        ),
        migrations.AlterField(
            model_name='men',
            name='time_create',
            field=models.DateField(auto_now_add=True, verbose_name='post created'),
        ),
        migrations.AlterField(
            model_name='men',
            name='title',
            field=models.CharField(max_length=255, verbose_name='title'),
        ),
    ]
